print(" Write a NumPy program to add a border (filled with 0's) around an existing array. ")
print("Expected Output: Original array: [[ 1. 1. 1.] [ 1. 1. 1.] [ 1. 1. 1.]] 1 on the border and 0 inside in the array [[ 0. 0. 0. 0. 0.] ........... [ 0. 0. 0. 0. 0.]]")
print("Escriba un programa NumPy para agregar un borde (lleno de ceros) alrededor de una matriz existente.")
print("Resultado esperado: Matriz original: [[1. 1. 1.] [1. 1. 1.] [1. 1. 1.]] 1 en el borde y 0 en el interior de la matriz [[0. 0. 0. 0. 0.] ........... [0. 0. 0. 0. 0.]]")
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)